global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Webhook Listener Metrics
  - job_name: 'webhook-listener'
    static_configs:
      - targets: ['webhook-listener:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # RabbitMQ Metrics
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']

  # RabbitMQ Management Metrics
  - job_name: 'rabbitmq-management'
    static_configs:
      - targets: ['rabbitmq:15672']
    metrics_path: '/api/metrics'
    basic_auth:
      username: 'gdrive_user'
      password: 'gdrive_pass123'

  # PostgreSQL Metrics (if postgres_exporter added)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Alert rules
# rule_files:
#   - "alert_rules.yml"