{{- if .Values.autoScheduler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gdrive-s3-sync.fullname" . }}-scheduler
  labels:
    {{- include "gdrive-s3-sync.labels" . | nindent 4 }}
    app.kubernetes.io/component: auto-scheduler
spec:
  replicas: {{ .Values.autoScheduler.replicaCount }}
  selector:
    matchLabels:
      {{- include "gdrive-s3-sync.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: auto-scheduler
  template:
    metadata:
      labels:
        {{- include "gdrive-s3-sync.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: auto-scheduler
    spec:
      containers:
        - name: auto-scheduler
          image: "{{ .Values.autoScheduler.image.repository }}:{{ .Values.autoScheduler.image.tag }}"
          imagePullPolicy: {{ .Values.autoScheduler.image.pullPolicy }}
          env:
            # Core environment
            - name: ENV
              value: {{ .Values.environment | quote }}
            - name: GDRIVE_FOLDER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "gdrive-s3-sync.fullname" . }}-secrets
                  key: gdrive-folder-id
            - name: AWS_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: {{ include "gdrive-s3-sync.fullname" . }}-secrets
                  key: aws-s3-bucket
            - name: WEBHOOK_URL
              value: "http://{{ include "gdrive-s3-sync.fullname" . }}-webhook:{{ .Values.webhookListener.service.port }}/webhook"
            - name: SYNC_CHECK_INTERVAL_MINUTES
              value: {{ .Values.config.gdrive.checkIntervalMinutes | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.config.scheduler.logLevel | quote }}
            - name: PYTHONPATH
              value: "/app"
          resources:
            {{- toYaml .Values.autoScheduler.resources | nindent 12 }}
{{- end }}
