apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gdrive-s3-sync.fullname" . }}-secrets
  labels:
    {{- include "gdrive-s3-sync.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Development values (production'da SOPS ile override edilecek)
  gdrive-folder-id: "1TcG_cbVfaRvPUyaPaqyPZVEd5p_eA_s_"
  aws-s3-bucket: "gdrive-sync-dev"
  aws-region: "eu-central-1"
  webhook-verification-token: "dev_webhook_token_2025"
