{{- if .Values.webhookListener.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gdrive-s3-sync.fullname" . }}-webhook
  labels:
    {{- include "gdrive-s3-sync.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook-listener
spec:
  replicas: {{ .Values.webhookListener.replicaCount }}
  selector:
    matchLabels:
      {{- include "gdrive-s3-sync.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: webhook-listener
  template:
    metadata:
      labels:
        {{- include "gdrive-s3-sync.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: webhook-listener
    spec:
      containers:
        - name: webhook-listener
          image: "{{ .Values.webhookListener.image.repository }}:{{ .Values.webhookListener.image.tag }}"
          imagePullPolicy: {{ .Values.webhookListener.image.pullPolicy }}
          ports:
            - name: webhook-port
              containerPort: 5000
              protocol: TCP
          env:
            - name: ENV
              value: {{ .Values.environment | quote }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rabbitmq
                  key: rabbitmq-password
            - name: RABBITMQ_URL
              value: "amqp://gdrive_user:$(RABBITMQ_PASSWORD)@{{ .Release.Name }}-rabbitmq:5672/"
            - name: GDRIVE_FOLDER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "gdrive-s3-sync.fullname" . }}-secrets
                  key: gdrive-folder-id
            - name: AWS_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: {{ include "gdrive-s3-sync.fullname" . }}-secrets
                  key: aws-s3-bucket
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ include "gdrive-s3-sync.fullname" . }}-secrets
                  key: aws-region
            - name: WEBHOOK_VERIFICATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "gdrive-s3-sync.fullname" . }}-secrets
                  key: webhook-verification-token
            - name: WEBHOOK_HOST
              value: "0.0.0.0"
            - name: WEBHOOK_PORT
              value: "5000"
            - name: LOG_LEVEL
              value: {{ .Values.config.webhook.logLevel | quote }}
            - name: PYTHONPATH
              value: "/app"
          livenessProbe:
            httpGet:
              path: /health
              port: webhook-port
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: webhook-port
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.webhookListener.resources | nindent 12 }}
{{- end }}
