apiVersion: v2
name: gdrive-s3-sync
description: A Helm chart for Google Drive to S3 Sync application
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: GDrive-S3-Sync Team
    email: team@gdrive-s3-sync.com
keywords:
  - gdrive
  - s3
  - sync
  - microservices
  - 12-factor
home: https://github.com/your-org/gdrive-s3-sync
sources:
  - https://github.com/your-org/gdrive-s3-sync

dependencies:
  - name: postgresql
    version: 13.2.24
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 18.4.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: rabbitmq
    version: 12.5.5
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
