#ENC[AES256_GCM,data:H3qHjD35Mz4pMX3T1jBGuhFT+UB66K7SjRLnmQXT1g==,iv:+mf+ckhx3PLNdJ9guKFceM0kRZVuJtmX/RqJgFgf0cA=,tag:i8+dMczdsRpF3kskGqAsgQ==,type:comment]
secrets:
    gdrive:
        folderId: ENC[AES256_GCM,data:k6yB0MniB7rlQC61wZdecJvaDfKT56qdq8VRV1FY,iv:7gwT9Nj7us6RZz3gygKt7J0q5tXxOoicl/zQDrDx+4o=,tag:Akqr//I67A1JzO/JFfhSAQ==,type:str]
    aws:
        s3Bucket: ENC[AES256_GCM,data:ak8qtTau5+BDC6EX+ifiUpYtWSW+Jw==,iv:mDaL+okM1n/zVurMMrUofkNPpi6Xza173xblnABbLG0=,tag:VDp7HDNpX4YiYPb3HSm/mg==,type:str]
        region: ENC[AES256_GCM,data:bo+xe2/JjdhS0DbT,iv:FqIHQkONOdWx7AfeHtMMULeFnArUixMRfjIQwx54OSA=,tag:ikO7ACLdCYwtkxG0AQhbqA==,type:str]
        accessKeyId: ENC[AES256_GCM,data:ykRM07COiFOjWqV+iv/0Ex2lUA2c,iv:GuDyM8P5Elwt+XELS8M1IBIcg92o4/yL395w08IKqgM=,tag:xbfeuuKJdshAoGDlfbPacA==,type:str]
        secretAccessKey: ENC[AES256_GCM,data:u4+4pZRwVGuEdiwXU32r84IRlM5C2U943IT07xZV,iv:TzJdnGzTKGWLFeaCsOz1VFiQgYMLN45bpVgBhJ7PwgI=,tag:rXRikkjxvKL1z5xbuD7XNQ==,type:str]
    webhook:
        verificationToken: ENC[AES256_GCM,data:qbGwiq2zcWLxQJQpk8/infi8/ZtOyS7QvnGxU0f0SdIqIZki,iv:T5mWznmIqioXsujJ5Mp3UBaoLZq2Y8LQTqHC4b/XiDs=,tag:9ezYqH7XcRWK0Y8teP6YEw==,type:str]
    database:
        postgresPassword: ENC[AES256_GCM,data:4rh0F2LWEsGy3wuzOFaZ1B3CCeN9fb4Mv7eEfa5i/OqLpZ8=,iv:t89LJrzLC/i4YsYjOIqHZMBvEieNiPnM/RDGNa7fIUQ=,tag:LMKfF+ztqkdJpKyQzqlL/A==,type:str]
        redisPassword: ENC[AES256_GCM,data:2QYMk/0Gth5b4FQ0lSQ+AZWo2msF5NLmelRjlDMPRbM=,iv:QUYkyr4pBAOovFvVROl1rslTrlcffEOMCRj93e3vNw0=,tag:4KEGOHEKLoVTNThSHntg5g==,type:str]
        rabbitmqPassword: ENC[AES256_GCM,data:gSseZxpqfqeF0ThlR55wd5rGy2gNqNTBIDYLoKSV9C033gs=,iv:B8lqHKqHJylac5S32Ggtt1sL+97OcgmwJUihrhRjSUE=,tag:LX8LeEkcPzM+YpZJMvFADw==,type:str]
#ENC[AES256_GCM,data:aXRlT4HKp2fikDo6qn6gZQRkzqmaa8REV8v/Rfk8FlY=,iv:T5pP4Z3Uft4h/xEVOQabYJZQsQA6MF1ZPiI8wEBWtto=,tag:ERHax++GckliiAP6c3Gj5w==,type:comment]
environment: ENC[AES256_GCM,data:XkKKseM2SsWi1w==,iv:NSS4XrasnwljsGCEupoAPZTJF/EZ/wnL3fUuo76okqI=,tag:kZXkyVqffhxU1Hes8Sb6Jg==,type:str]
webhookListener:
    replicaCount: ENC[AES256_GCM,data:HA==,iv:0pFwYTzHa1SZ13GGriOhCTv85ATRH+PvlFote2BmTQA=,tag:QDEOv3vAMd4EF0e3UhWGdA==,type:int]
s3Uploader:
    replicaCount: ENC[AES256_GCM,data:UQ==,iv:tCoIWldJ95rDdQx9Xp2hNZucjyNT4p0BmhjL9no4els=,tag:TGnof4jJNPRf3dMrTbc2PA==,type:int]
autoScheduler:
    replicaCount: ENC[AES256_GCM,data:XQ==,iv:biREYqdhk2XT9cSCn2kSb2IH3HDAE0UDk23Fq/gfwCE=,tag:yxpGRVu6dAsLwbx8fxvS+Q==,type:int]
sops:
    age:
        - recipient: age1u40ahvntcm4lhr4ej4hr39ertm9nr98kfvssqtv0gqkad35u444slqgase
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMVhZa3NlTWtYVnBuak5V
            bmxsdERicythZTBIYmZHWE9rUVhvL2NRV2dRCkZ0Q1IrQytOajBCQXhYcUtqWXlM
            NWxFRlkyT0h2T0lRVytKcm1vYWx0T2sKLS0tIEZZaGFqeDRPTGRsckJFNmlTS1Ux
            L0xYZTR1MUErQm1XTXRWTHlRbGxJMVkKnuMOG+1LAysxA0BpgbnJ6+6LOR3V3elF
            GYrwY9bpvS7FNmRFLgS58fZlKFdsMWWdTcV04/i6cidiKo7ZhU2fMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-21T10:40:22Z"
    mac: ENC[AES256_GCM,data:iOTMYpLtjjjpOp8XmnSt9uhYi3JA1cu4f2Vz2EFLtBreFqyQBoaY2Hihv4YHXic0pcKSpN9FO1rfu3VYnLCxPjMS7+Uc3D5/R3OeM3piYf41B/BB1b0wsQk4u8PMl/s1pANOTWCy8BHF6ncFISOF8kwzPHeUr7TyW1Sggs/3br8=,iv:F2QOZS+skGTH8fCgcgRDnx5s77x9J7/Zf3PG4DqPr94=,tag:C2g4i5TF/q2yaYLPw398GA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
